/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Phan Van Phuc
 */
public class QuanLyNhanSuView extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyNhanSuView
     */
    public QuanLyNhanSuView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnqlcb = new javax.swing.JButton();
        btnqll = new javax.swing.JButton();
        btnqlkt = new javax.swing.JButton();
        btnqlcbpb = new javax.swing.JButton();
        btnquaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnqlcb.setText("QUAN LY CAN BO");
        btnqlcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlcbActionPerformed(evt);
            }
        });

        btnqll.setText("QUAN LY LUONG");
        btnqll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqllActionPerformed(evt);
            }
        });

        btnqlkt.setText("QUAN LY KHEN THUONG");
        btnqlkt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlktActionPerformed(evt);
            }
        });

        btnqlcbpb.setText("QUAN LY CHUC VU PHONG BAN");
        btnqlcbpb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnqlcbpbActionPerformed(evt);
            }
        });

        btnquaylai.setText("quaylai");
        btnquaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnqll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnqlcb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnqlkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnqlcbpb, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnquaylai)
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnqlcb)
                .addGap(43, 43, 43)
                .addComponent(btnqll)
                .addGap(44, 44, 44)
                .addComponent(btnqlkt)
                .addGap(34, 34, 34)
                .addComponent(btnqlcbpb)
                .addGap(18, 18, 18)
                .addComponent(btnquaylai)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnqlcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlcbActionPerformed
        try {
            new QuanLyCanBoView().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnqlcbActionPerformed

    private void btnqllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqllActionPerformed
        new QuanLyLuongView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnqllActionPerformed

    private void btnquaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquaylaiActionPerformed
        new QuanLyView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnquaylaiActionPerformed

    private void btnqlktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlktActionPerformed
       new QuanLyKhenThuongView().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnqlktActionPerformed

    private void btnqlcbpbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnqlcbpbActionPerformed
        new QuanLyCvPbView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnqlcbpbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanSuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyNhanSuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnqlcb;
    private javax.swing.JButton btnqlcbpb;
    private javax.swing.JButton btnqlkt;
    private javax.swing.JButton btnqll;
    private javax.swing.JButton btnquaylai;
    // End of variables declaration//GEN-END:variables
}
